apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rqgz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0011-tenant/tkrw-pr712-0075-0011-app/devfile-sample-rqgz@sha256:cbcbdc48ae9480dbb5311651a4eed07be70589aba76991cd35b9db49e7fde6b5
        name: my-nodejs
        resources: {}
status: {}
